czritual_standard.wad
czcs_italy.wad
czcs_office.wad
gfx/detail/dt_carpet1.tga
gfx/detail/dt_fabric1.tga
gfx/detail/dt_fabric2.tga
gfx/detail/dt_ground3.tga
gfx/detail/dt_ground4.tga
gfx/detail/dt_metal1.tga
gfx/detail/dt_metal2.tga
gfx/detail/dt_smooth1.tga
gfx/detail/dt_snow2.tga
gfx/detail/dt_ssteel1.tga
gfx/detail/dt_stone1.tga
gfx/detail/dt_stone2.tga
gfx/detail/dt_stone3.tga
gfx/detail/dt_wood1.tga
gfx/detail/dt_wood2.tga
gfx/detail/dt_wood3.tga
gfx/env/winter_xboxbk.tga
gfx/env/winter_xboxdn.tga
gfx/env/winter_xboxft.tga
gfx/env/winter_xboxlf.tga
gfx/env/winter_xboxrt.tga
gfx/env/winter_xboxup.tga
models/props/ac_large.mdl
models/props/chair_office.mdl
models/props/couch_leather-black.mdl
models/props/couch_leather.mdl
models/props/lamp_hanging-industrial.mdl
models/props/machinery_static.mdl
models/props/pallet_stack.mdl
models/props/trash.mdl
models/props/trash_trashcan.mdl
models/props/tree_noleaves2.mdl
overviews/cs_office_cz.bmp
overviews/cs_office_cz.txt