czritual_standard.wad
czcs_italy.wad
gfx/detail/dt_carpet1.tga
gfx/detail/dt_fabric1.tga
gfx/detail/dt_fabric2.tga
gfx/detail/dt_metal1.tga
gfx/detail/dt_metal2.tga
gfx/detail/dt_plaster1.tga
gfx/detail/dt_plaster2.tga
gfx/detail/dt_smooth1.tga
gfx/detail/dt_snow2.tga
gfx/detail/dt_stone1.tga
gfx/detail/dt_stone2.tga
gfx/detail/dt_wood.tga
gfx/detail/dt_wood1.tga
gfx/detail/dt_wood2.tga
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
hlbasics.wad
models/props/lamp_street-euro2.mdl
models/props/lamp_street-euro2a.mdl
overviews/cs_italy_cz.bmp
overviews/cs_italy_cz.txt