czritual_standard.wad
czde_airstrip.wad
gfx/detail/dt_grass1.tga
gfx/detail/dt_ground2.tga
gfx/detail/dt_metal1.tga
gfx/detail/dt_metal2.tga
gfx/detail/dt_smooth1.tga
gfx/detail/dt_snow2.tga
gfx/detail/dt_stone1.tga
gfx/detail/dt_stone2.tga
gfx/detail/dt_stone3.tga
gfx/detail/dt_wood1.tga
gfx/detail/dt_wood2.tga
overviews/de_airstrip_cz.bmp
overviews/de_airstrip_cz.txt