czritual_standard.wad
czde_prodigy.wad
gfx/detail/dt_ground1.tga
gfx/detail/dt_ground2.tga
gfx/detail/dt_ground3.tga
gfx/detail/dt_metal1.tga
gfx/detail/dt_metal2.tga
gfx/detail/dt_plaster1.tga
gfx/detail/dt_plaster2.tga
gfx/detail/dt_rock1.tga
gfx/detail/dt_smooth1.tga
gfx/detail/dt_snow2.tga
gfx/detail/dt_stone1.tga
gfx/detail/dt_stone2.tga
gfx/detail/dt_stone3.tga
gfx/detail/dt_wood1.tga
gfx/detail/dt_wood2.tga
hlbasics.wad
models/props/apc_desert.mdl
overviews/de_prodigy_cz.bmp
overviews/de_prodigy_cz.txt