czritual_standard.wad
czde_sienna.wad
gfx/detail/dt_carpet1.tga
gfx/detail/dt_conc.tga
gfx/detail/dt_grass1.tga
gfx/detail/dt_ground1.tga
gfx/detail/dt_metal2.tga
gfx/detail/dt_plaster2.tga
gfx/detail/dt_rock1.tga
gfx/detail/dt_stone2.tga
gfx/detail/dt_stone3.tga
gfx/detail/dt_stone4.tga
gfx/detail/dt_wood.tga
gfx/detail/dt_wood1.tga
gfx/detail/dt_wood2.tga
gfx/env/siennabk.tga
gfx/env/siennadn.tga
gfx/env/siennaft.tga
gfx/env/siennalf.tga
gfx/env/siennart.tga
gfx/env/siennaup.tga
hlbasics.wad
overviews/de_sienna_cz.bmp
overviews/de_sienna_cz.txt